# Generated by Django 3.2.9 on 2021-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_coverage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragetype',
            name='coverage_site',
        ),
        migrations.AddField(
            model_name='coveragesite',
            name='coverage_types',
            field=models.ManyToManyField(to='location_coverage.CoverageType'),
        ),
    ]
