# Generated by Django 3.2.9 on 2021-11-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_coverage', '0002_auto_20211111_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveragesite',
            old_name='x_coordinates',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='coveragesite',
            old_name='y_coordinates',
            new_name='long',
        ),
    ]
