# Generated by Django 3.2.9 on 2021-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_coverage', '0005_auto_20211116_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragesite',
            name='lat',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='coveragesite',
            name='long',
            field=models.CharField(max_length=19),
        ),
    ]
